<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\BoilerplateCategoryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\BoilerplateGroupInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\BoilerplateInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\TagInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<BoilerplateInterface>
 *
 * @property-read AttributeConfigBuilderInterface<BoilerplateInterface> $ident
 * @property-read ToOneRelationshipConfigBuilderInterface<BoilerplateInterface,ProcedureInterface> $procedure
 * @property-read ToManyRelationshipConfigBuilderInterface<BoilerplateInterface,BoilerplateCategoryInterface> $categories
 * @property-read ToOneRelationshipConfigBuilderInterface<BoilerplateInterface,BoilerplateGroupInterface> $group
 * @property-read ToManyRelationshipConfigBuilderInterface<BoilerplateInterface,TagInterface> $tags
 * @property-read AttributeConfigBuilderInterface<BoilerplateInterface> $title
 * @property-read AttributeConfigBuilderInterface<BoilerplateInterface> $text
 * @property-read AttributeConfigBuilderInterface<BoilerplateInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<BoilerplateInterface> $modifyDate
 */
class BaseBoilerplateResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
