<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\DepartmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DraftStatementFileInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DraftStatementInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DraftStatementVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ElementsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ParagraphVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SingleDocumentVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementAttributeInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<DraftStatementInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementInterface,ProcedureInterface> $procedure
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $number
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $title
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $text
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementInterface,ParagraphVersionInterface> $paragraph
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementInterface,SingleDocumentVersionInterface> $document
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementInterface,ElementsInterface> $element
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $polygon
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $file
 * @property-read ToManyRelationshipConfigBuilderInterface<DraftStatementInterface,DraftStatementFileInterface> $files
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $mapFile
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementInterface,OrgaInterface> $organisation
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $oName
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $dName
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementInterface,DepartmentInterface> $department
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementInterface,UserInterface> $user
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $uName
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $uStreet
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $houseNumber
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $uPostalCode
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $uCity
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $uEmail
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $uFeedback
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $feedback
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $externId
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $rejectedReason
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $negativ
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $submitted
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $released
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $showToAll
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $rejected
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $publicAllowed
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $publicUseName
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $publicDraftStatement
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $represents
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $phase
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $deletedDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $lastModifiedDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $submittedDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $releasedDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $rejectedDate
 * @property-read ToManyRelationshipConfigBuilderInterface<DraftStatementInterface,DraftStatementVersionInterface> $versions
 * @property-read ToManyRelationshipConfigBuilderInterface<DraftStatementInterface,StatementAttributeInterface> $statementAttributes
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $miscData
 * @property-read AttributeConfigBuilderInterface<DraftStatementInterface> $anonymous
 */
class BaseDraftStatementResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
