<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\EntitySyncLinkInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<EntitySyncLinkInterface>
 *
 * @property-read AttributeConfigBuilderInterface<EntitySyncLinkInterface> $class
 * @property-read AttributeConfigBuilderInterface<EntitySyncLinkInterface> $sourceId
 * @property-read AttributeConfigBuilderInterface<EntitySyncLinkInterface> $targetId
 */
class BaseEntitySyncLinkResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
