<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\StatementInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementMetaInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<StatementMetaInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementMetaInterface,StatementInterface> $statement
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $authorName
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $authorFeedback
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $submitUId
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $submitName
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $orgaName
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $orgaDepartmentName
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $caseWorkerName
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $orgaStreet
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $houseNumber
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $orgaPostalCode
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $orgaCity
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $orgaEmail
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $authoredDate
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $submitOrgaId
 * @property-read AttributeConfigBuilderInterface<StatementMetaInterface> $miscData
 */
class BaseStatementMetaResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
