<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\OriginalStatementAnonymizationInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<OriginalStatementAnonymizationInterface>
 *
 * @property-read AttributeConfigBuilderInterface<OriginalStatementAnonymizationInterface> $created
 * @property-read ToOneRelationshipConfigBuilderInterface<OriginalStatementAnonymizationInterface,StatementInterface> $statement
 * @property-read ToOneRelationshipConfigBuilderInterface<OriginalStatementAnonymizationInterface,UserInterface> $createdBy
 * @property-read AttributeConfigBuilderInterface<OriginalStatementAnonymizationInterface> $attachmentsDeleted
 * @property-read AttributeConfigBuilderInterface<OriginalStatementAnonymizationInterface> $textVersionHistoryDeleted
 * @property-read AttributeConfigBuilderInterface<OriginalStatementAnonymizationInterface> $textPassagesAnonymized
 * @property-read AttributeConfigBuilderInterface<OriginalStatementAnonymizationInterface> $submitterAndAuthorMetaDataAnonymized
 */
class BaseOriginalStatementAnonymizationResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
