<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\FileContainerInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\FileInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<FileContainerInterface>
 *
 * @property-read AttributeConfigBuilderInterface<FileContainerInterface> $entityId
 * @property-read AttributeConfigBuilderInterface<FileContainerInterface> $entityClass
 * @property-read AttributeConfigBuilderInterface<FileContainerInterface> $entityField
 * @property-read AttributeConfigBuilderInterface<FileContainerInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<FileContainerInterface> $modifyDate
 * @property-read AttributeConfigBuilderInterface<FileContainerInterface> $order
 * @property-read AttributeConfigBuilderInterface<FileContainerInterface> $fileString
 * @property-read ToOneRelationshipConfigBuilderInterface<FileContainerInterface,FileInterface> $file
 * @property-read AttributeConfigBuilderInterface<FileContainerInterface> $publicAllowed
 */
class BaseFileContainerResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
