<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\FileInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,FileInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $ident
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $hash
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $name
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $description
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $path
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $filename
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $tags
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $author
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $application
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $mimetype
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $created
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $modified
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $validUntil
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $statDown
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $infected
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $lastVScan
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $blocked
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileInterface> $size
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,FileInterface,ProcedureInterface> $procedure
 */
class BaseFileResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
