<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ExportFieldsConfigurationInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ExportFieldsConfigurationInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ExportFieldsConfigurationInterface,ProcedureInterface> $procedure
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $creationDate
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $modificationDate
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $idExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $statementNameExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $creationDateExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $procedureNameExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $procedurePhaseExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $votesNumExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $userStateExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $userGroupExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $userOrganisationExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $userPositionExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $institutionExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $publicParticipationExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $orgaNameExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $departmentNameExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $submitterNameExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $showInPublicAreaExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $documentExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $paragraphExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $filesExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $attachmentsExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $priorityExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $emailExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $phoneNumberExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $streetExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $streetNumberExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $postalCodeExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $cityExportable
 * @property-read AttributeConfigBuilderInterface<ExportFieldsConfigurationInterface> $institutionOrCitizenExportable
 */
class BaseExportFieldsConfigurationResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
