<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureSettingsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureSettingsInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $mapExtent
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $startScale
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $availableScale
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $boundingBox
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $informationUrl
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $defaultLayer
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $territory
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $coordinate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $planEnable
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $planText
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $planPDF
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $planPara1PDF
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $planPara2PDF
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $planDrawText
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $planDrawPDF
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $emailTitle
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $emailText
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $emailCc
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $links
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureSettingsInterface,ProcedureInterface> $procedure
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $pictogram
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $designatedPhase
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $designatedPublicPhase
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $designatedSwitchDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $designatedPublicSwitchDate
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureSettingsInterface,UserInterface> $designatedPhaseChangeUser
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureSettingsInterface,UserInterface> $designatedPublicPhaseChangeUser
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $designatedEndDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $designatedPublicEndDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $sendMailsToCounties
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $planningArea
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $scales
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $legalNotice
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $copyright
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSettingsInterface> $mapHint
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureSettingsInterface,ProcedureInterface> $allowedSegmentAccessProcedures
 */
class BaseProcedureSettingsResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
