<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\NewsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\RoleInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<NewsInterface>
 *
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $ident
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $pId
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $title
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $description
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $text
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $picture
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $pictitle
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $pdf
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $pdftitle
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $enabled
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $modifyDate
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $deleteDate
 * @property-read ToManyRelationshipConfigBuilderInterface<NewsInterface,RoleInterface> $roles
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $designatedSwitchDate
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $designatedState
 * @property-read AttributeConfigBuilderInterface<NewsInterface> $determinedToSwitch
 */
class BaseNewsResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
