<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\AddressInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DepartmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DepartmentInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DepartmentInterface> $name
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DepartmentInterface> $code
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DepartmentInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DepartmentInterface> $modifiedDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DepartmentInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DepartmentInterface> $gwId
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DepartmentInterface,OrgaInterface> $orgas
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DepartmentInterface,AddressInterface> $addresses
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DepartmentInterface,UserInterface> $users
 */
class BaseDepartmentResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
