<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\TagInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\TagTopicInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<TagTopicInterface>
 *
 * @property-read AttributeConfigBuilderInterface<TagTopicInterface> $title
 * @property-read AttributeConfigBuilderInterface<TagTopicInterface> $createDate
 * @property-read ToOneRelationshipConfigBuilderInterface<TagTopicInterface,ProcedureInterface> $procedure
 * @property-read ToManyRelationshipConfigBuilderInterface<TagTopicInterface,TagInterface> $tags
 */
class BaseTagTopicResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
