<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\CustomerInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ElementsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\EmailAddressInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ExportFieldsConfigurationInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\FileInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\NotificationReceiverInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\PlaceInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureBehaviorDefinitionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureCategoryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureSettingsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureTypeInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureUiDefinitionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SlugInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementFormDefinitionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SurveyInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\TagTopicInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $name
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $shortUrl
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $orgaName
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,OrgaInterface> $orga
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $desc
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $phase
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $step
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $logo
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $externId
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $plisId
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $closed
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $master
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $masterTemplate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $externalName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $externalDesc
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $publicParticipation
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $publicParticipationPhase
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $publicParticipationStep
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $publicParticipationStartDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $publicParticipationEndDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $publicParticipationContact
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $publicParticipationPublicationEnabled
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $locationName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $locationPostCode
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $municipalCode
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $ars
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $startDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $endDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $closedDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $deletedDate
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,OrgaInterface> $organisation
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,OrgaInterface> $planningOffices
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,OrgaInterface> $dataInputOrganisations
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,ProcedureSettingsInterface> $settings
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,TagTopicInterface> $topics
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,NotificationReceiverInterface> $notificationReceivers
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,ElementsInterface> $elements
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,UserInterface> $authorizedUsers
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $agencyMainEmailAddress
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,EmailAddressInterface> $agencyExtraEmailAddresses
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,CustomerInterface> $customer
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,ProcedureCategoryInterface> $procedureCategories
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,StatementInterface> $statements
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,SurveyInterface> $surveys
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,ProcedureTypeInterface> $procedureType
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,StatementFormDefinitionInterface> $statementFormDefinition
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,ProcedureBehaviorDefinitionInterface> $procedureBehaviorDefinition
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,ProcedureUiDefinitionInterface> $procedureUiDefinition
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,ExportFieldsConfigurationInterface> $exportFieldsConfigurations
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,FileInterface> $files
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureInterface> $xtaPlanId
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,PlaceInterface> $segmentPlaces
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,SlugInterface> $currentSlug
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureInterface,SlugInterface> $slugs
 */
class BaseProcedureResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
