<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\DevelopmentReleaseInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DevelopmentUserStoryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ForumThreadInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentUserStoryInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryInterface> $ident
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentUserStoryInterface,DevelopmentReleaseInterface> $release
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentUserStoryInterface,ForumThreadInterface> $thread
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryInterface> $onlineVotes
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryInterface> $offlineVotes
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryInterface> $description
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryInterface> $title
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryInterface> $modifiedDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryInterface> $createDate
 */
class BaseDevelopmentUserStoryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
