<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\StatementInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementVersionFieldInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementVersionFieldInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionFieldInterface> $userIdent
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionFieldInterface> $userName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionFieldInterface> $sessionIdent
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionFieldInterface> $name
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionFieldInterface> $type
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionFieldInterface> $value
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionFieldInterface> $created
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementVersionFieldInterface,StatementInterface> $statement
 */
class BaseStatementVersionFieldResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
