<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\PlaceInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SegmentCommentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SegmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<SegmentCommentInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<SegmentCommentInterface,SegmentInterface> $segment
 * @property-read ToOneRelationshipConfigBuilderInterface<SegmentCommentInterface,UserInterface> $submitter
 * @property-read ToOneRelationshipConfigBuilderInterface<SegmentCommentInterface,PlaceInterface> $place
 * @property-read AttributeConfigBuilderInterface<SegmentCommentInterface> $creationDate
 * @property-read AttributeConfigBuilderInterface<SegmentCommentInterface> $text
 */
class BaseSegmentCommentResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
