<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\HashedQueryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserFilterSetInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<UserFilterSetInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<UserFilterSetInterface,UserInterface> $user
 * @property-read AttributeConfigBuilderInterface<UserFilterSetInterface> $name
 * @property-read ToOneRelationshipConfigBuilderInterface<UserFilterSetInterface,HashedQueryInterface> $filterSet
 * @property-read ToOneRelationshipConfigBuilderInterface<UserFilterSetInterface,ProcedureInterface> $procedure
 */
class BaseUserFilterSetResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
