<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\AddressBookEntryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\AddressInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\BrandingInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DepartmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\InstitutionTagInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\MasterToebInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaStatusInCustomerInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SlugInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<OrgaInterface>
 *
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $name
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $gatewayName
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $code
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $modifiedDate
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $ccEmail2
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $emailReviewerAdmin
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $showname
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $showlist
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $gwId
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $competence
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $email2
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $contactPerson
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $paperCopy
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $paperCopySpec
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaInterface,AddressInterface> $addresses
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $dataProtection
 * @property-read AttributeConfigBuilderInterface<OrgaInterface> $imprint
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaInterface,UserInterface> $users
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaInterface,DepartmentInterface> $departments
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaInterface,ProcedureInterface> $procedures
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaInterface,ProcedureInterface> $procedureInvitations
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaInterface,AddressBookEntryInterface> $addressBookEntries
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaInterface,OrgaStatusInCustomerInterface> $statusInCustomers
 * @property-read ToOneRelationshipConfigBuilderInterface<OrgaInterface,MasterToebInterface> $masterToeb
 * @property-read ToOneRelationshipConfigBuilderInterface<OrgaInterface,BrandingInterface> $branding
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaInterface,ProcedureInterface> $administratableProcedures
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaInterface,InstitutionTagInterface> $assignedTags
 * @property-read ToOneRelationshipConfigBuilderInterface<OrgaInterface,SlugInterface> $currentSlug
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaInterface,SlugInterface> $slugs
 */
class BaseOrgaResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
