<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\GisLayerCategoryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\GisLayerInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GisLayerCategoryInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GisLayerCategoryInterface,ProcedureInterface> $procedure
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategoryInterface> $name
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategoryInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategoryInterface> $modifyDate
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GisLayerCategoryInterface,GisLayerInterface> $gisLayers
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GisLayerCategoryInterface,GisLayerCategoryInterface> $parent
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GisLayerCategoryInterface,GisLayerCategoryInterface> $children
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategoryInterface> $treeOrder
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategoryInterface> $visible
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategoryInterface> $layerWithChildrenHidden
 */
class BaseGisLayerCategoryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
