<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\AddressBookEntryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<AddressBookEntryInterface>
 *
 * @property-read AttributeConfigBuilderInterface<AddressBookEntryInterface> $name
 * @property-read ToOneRelationshipConfigBuilderInterface<AddressBookEntryInterface,OrgaInterface> $organisation
 * @property-read AttributeConfigBuilderInterface<AddressBookEntryInterface> $emailAddress
 * @property-read AttributeConfigBuilderInterface<AddressBookEntryInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<AddressBookEntryInterface> $modifiedDate
 */
class BaseAddressBookEntryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
