<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ForumEntryFileInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ForumEntryInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ForumEntryFileInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ForumEntryFileInterface> $ident
 * @property-read AttributeConfigBuilderInterface<ForumEntryFileInterface> $entryId
 * @property-read ToOneRelationshipConfigBuilderInterface<ForumEntryFileInterface,ForumEntryInterface> $entry
 * @property-read AttributeConfigBuilderInterface<ForumEntryFileInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<ForumEntryFileInterface> $modifyDate
 * @property-read AttributeConfigBuilderInterface<ForumEntryFileInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ForumEntryFileInterface> $blocked
 * @property-read AttributeConfigBuilderInterface<ForumEntryFileInterface> $order
 * @property-read AttributeConfigBuilderInterface<ForumEntryFileInterface> $string
 * @property-read AttributeConfigBuilderInterface<ForumEntryFileInterface> $hash
 */
class BaseForumEntryFileResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
