<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\FloodInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<FloodInterface>
 *
 * @property-read AttributeConfigBuilderInterface<FloodInterface> $event
 * @property-read AttributeConfigBuilderInterface<FloodInterface> $identifier
 * @property-read AttributeConfigBuilderInterface<FloodInterface> $created
 * @property-read AttributeConfigBuilderInterface<FloodInterface> $expires
 */
class BaseFloodResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
