<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ElementsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ParagraphInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ParagraphVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ParagraphInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ParagraphInterface,ProcedureInterface> $procedure
 * @property-read ToOneRelationshipConfigBuilderInterface<ParagraphInterface,ParagraphInterface> $parent
 * @property-read ToManyRelationshipConfigBuilderInterface<ParagraphInterface,ParagraphInterface> $children
 * @property-read ToOneRelationshipConfigBuilderInterface<ParagraphInterface,ElementsInterface> $element
 * @property-read AttributeConfigBuilderInterface<ParagraphInterface> $category
 * @property-read AttributeConfigBuilderInterface<ParagraphInterface> $title
 * @property-read AttributeConfigBuilderInterface<ParagraphInterface> $text
 * @property-read AttributeConfigBuilderInterface<ParagraphInterface> $order
 * @property-read AttributeConfigBuilderInterface<ParagraphInterface> $visible
 * @property-read AttributeConfigBuilderInterface<ParagraphInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ParagraphInterface> $lockReason
 * @property-read AttributeConfigBuilderInterface<ParagraphInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<ParagraphInterface> $modifyDate
 * @property-read AttributeConfigBuilderInterface<ParagraphInterface> $deleteDate
 * @property-read ToManyRelationshipConfigBuilderInterface<ParagraphInterface,ParagraphVersionInterface> $versions
 */
class BaseParagraphResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
