<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\AddressInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DepartmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SurveyVoteInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserRoleInCustomerInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<UserInterface>
 *
 * @property-read AttributeConfigBuilderInterface<UserInterface> $dmId
 * @property-read AttributeConfigBuilderInterface<UserInterface> $gender
 * @property-read AttributeConfigBuilderInterface<UserInterface> $title
 * @property-read AttributeConfigBuilderInterface<UserInterface> $firstname
 * @property-read AttributeConfigBuilderInterface<UserInterface> $lastname
 * @property-read AttributeConfigBuilderInterface<UserInterface> $email
 * @property-read AttributeConfigBuilderInterface<UserInterface> $login
 * @property-read AttributeConfigBuilderInterface<UserInterface> $password
 * @property-read AttributeConfigBuilderInterface<UserInterface> $alternativeLoginPassword
 * @property-read AttributeConfigBuilderInterface<UserInterface> $salt
 * @property-read AttributeConfigBuilderInterface<UserInterface> $language
 * @property-read AttributeConfigBuilderInterface<UserInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<UserInterface> $modifiedDate
 * @property-read AttributeConfigBuilderInterface<UserInterface> $lastLogin
 * @property-read AttributeConfigBuilderInterface<UserInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<UserInterface> $gwId
 * @property-read AttributeConfigBuilderInterface<UserInterface> $flags
 * @property-read ToManyRelationshipConfigBuilderInterface<UserInterface,OrgaInterface> $orga
 * @property-read ToManyRelationshipConfigBuilderInterface<UserInterface,DepartmentInterface> $departments
 * @property-read ToManyRelationshipConfigBuilderInterface<UserInterface,UserRoleInCustomerInterface> $roleInCustomers
 * @property-read ToManyRelationshipConfigBuilderInterface<UserInterface,AddressInterface> $addresses
 * @property-read ToManyRelationshipConfigBuilderInterface<UserInterface,SurveyVoteInterface> $surveyVotes
 * @property-read ToOneRelationshipConfigBuilderInterface<UserInterface,UserInterface> $twinUser
 * @property-read ToManyRelationshipConfigBuilderInterface<UserInterface,ProcedureInterface> $authorizedProcedures
 * @property-read AttributeConfigBuilderInterface<UserInterface> $providedByIdentityProvider
 */
class BaseUserResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
