<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\CustomerInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\RoleInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserRoleInCustomerInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<UserRoleInCustomerInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<UserRoleInCustomerInterface,UserInterface> $user
 * @property-read ToOneRelationshipConfigBuilderInterface<UserRoleInCustomerInterface,RoleInterface> $role
 * @property-read ToOneRelationshipConfigBuilderInterface<UserRoleInCustomerInterface,CustomerInterface> $customer
 */
class BaseUserRoleInCustomerResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
