<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureTypeInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureUiDefinitionInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureUiDefinitionInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinitionInterface> $creationDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinitionInterface> $modificationDate
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureUiDefinitionInterface,ProcedureInterface> $procedure
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureUiDefinitionInterface,ProcedureTypeInterface> $procedureType
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinitionInterface> $mapHintDefault
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinitionInterface> $statementFormHintStatement
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinitionInterface> $statementFormHintPersonalData
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinitionInterface> $statementFormHintRecheck
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinitionInterface> $statementPublicSubmitConfirmationText
 */
class BaseProcedureUiDefinitionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
