<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedurePersonInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ProcedurePersonInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ProcedurePersonInterface> $streetName
 * @property-read AttributeConfigBuilderInterface<ProcedurePersonInterface> $streetNumber
 * @property-read AttributeConfigBuilderInterface<ProcedurePersonInterface> $city
 * @property-read AttributeConfigBuilderInterface<ProcedurePersonInterface> $postalCode
 * @property-read AttributeConfigBuilderInterface<ProcedurePersonInterface> $emailAddress
 * @property-read ToManyRelationshipConfigBuilderInterface<ProcedurePersonInterface,StatementInterface> $similarForeignStatements
 * @property-read AttributeConfigBuilderInterface<ProcedurePersonInterface> $fullName
 * @property-read ToOneRelationshipConfigBuilderInterface<ProcedurePersonInterface,ProcedureInterface> $procedure
 */
class BaseProcedurePersonResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
