<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\CustomerInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\EmailAddressInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SupportContactInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SupportContactInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SupportContactInterface> $title
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SupportContactInterface> $phoneNumber
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SupportContactInterface,EmailAddressInterface> $eMailAddress
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SupportContactInterface> $text
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SupportContactInterface> $visible
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SupportContactInterface,CustomerInterface> $customer
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SupportContactInterface> $supportType
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SupportContactInterface> $createdAt
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SupportContactInterface> $updatedAt
 */
class BaseSupportContactResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
