<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\DepartmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ParagraphVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SingleDocumentVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementFragmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementFragmentVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersionInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersionInterface,StatementFragmentInterface> $statementFragment
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $displayId
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $text
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $tagAndTopicNames
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersionInterface,ProcedureInterface> $procedure
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $voteAdvice
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $vote
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $created
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $departmentName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $orgaName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $considerationAdvice
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $consideration
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $countyNames
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $priorityAreaKeys
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $municipalityNames
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $archivedOrgaName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $archivedDepartmentName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $archivedVoteUserName
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersionInterface,UserInterface> $modifiedByUser
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersionInterface,DepartmentInterface> $modifiedByDepartment
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $elementTitle
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersionInterface> $elementCategory
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersionInterface,ParagraphVersionInterface> $paragraph
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersionInterface,SingleDocumentVersionInterface> $document
 */
class BaseStatementFragmentVersionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
