<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\CategoryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\GlobalContentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\RoleInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GlobalContentInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $ident
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $type
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $title
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $description
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $text
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $picture
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $pictitle
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $pdf
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $pdftitle
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $enabled
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $modifyDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GlobalContentInterface> $deleteDate
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GlobalContentInterface,RoleInterface> $roles
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GlobalContentInterface,CategoryInterface> $categories
 */
class BaseGlobalContentResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
