<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\CategoryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\GlobalContentInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<CategoryInterface>
 *
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $name
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $title
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $description
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $picture
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $pictitle
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $enabled
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $modifyDate
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $deleteDate
 * @property-read ToManyRelationshipConfigBuilderInterface<CategoryInterface,GlobalContentInterface> $globalContents
 * @property-read AttributeConfigBuilderInterface<CategoryInterface> $custom
 */
class BaseCategoryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
