<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\CountyInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DraftStatementInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ElementsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\GdprConsentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\MunicipalityInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OriginalStatementAnonymizationInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ParagraphVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\PriorityAreaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedurePersonInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SegmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SingleDocumentVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementAttachmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementAttributeInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementFragmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementLikeInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementMetaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementVersionFieldInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementVoteInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\TagInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<StatementInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,StatementInterface> $parent
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,StatementInterface> $children
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,StatementInterface> $original
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,StatementInterface> $statementsCreatedFromOriginal
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $priority
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $externId
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $internId
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,UserInterface> $user
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,OrgaInterface> $organisation
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,ProcedureInterface> $procedure
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $represents
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $representationCheck
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $phase
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $status
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $created
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $modified
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $send
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $sentAssessmentDate
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $submit
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $deletedDate
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $negativeStatement
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $sentAssessment
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $publicUseName
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $publicVerified
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,OriginalStatementAnonymizationInterface> $anonymizations
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $publicStatement
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $toSendPerMail
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $title
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $text
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $recommendation
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $memo
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $feedback
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $reasonParagraph
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $planningDocument
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $file
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $mapFile
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $countyNotified
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,ParagraphVersionInterface> $paragraph
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,SingleDocumentVersionInterface> $document
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,ElementsInterface> $element
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $polygon
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,DraftStatementInterface> $draftStatement
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,StatementMetaInterface> $meta
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,StatementVersionFieldInterface> $version
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,StatementAttributeInterface> $statementAttributes
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,StatementVoteInterface> $votes
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $numberOfAnonymVotes
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,StatementLikeInterface> $likes
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,TagInterface> $tags
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,CountyInterface> $counties
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,PriorityAreaInterface> $priorityAreas
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,MunicipalityInterface> $municipalities
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,StatementFragmentInterface> $fragments
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $voteStk
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $votePla
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,GdprConsentInterface> $gdprConsent
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $submitType
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,UserInterface> $assignee
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,StatementInterface> $headStatement
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,StatementInterface> $cluster
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $manual
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $clusterStatement
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,StatementInterface> $placeholderStatement
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementInterface,StatementInterface> $movedStatement
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $name
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $replied
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $draftsListJson
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,SegmentInterface> $segmentsOfStatement
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,StatementAttachmentInterface> $attachments
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $segmentationPiRetries
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $piSegmentsProposalResourceUrl
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementInterface,ProcedurePersonInterface> $similarStatementSubmitters
 * @property-read AttributeConfigBuilderInterface<StatementInterface> $anonymous
 */
class BaseStatementResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
