<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\SessionsInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SessionsInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SessionsInterface> $sess_id
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SessionsInterface> $sess_data
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SessionsInterface> $sess_lifetime
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SessionsInterface> $sess_time
 */
class BaseSessionsResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
