<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ElementsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SingleDocumentInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ElementsInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $elementParentId
 * @property-read ToOneRelationshipConfigBuilderInterface<ElementsInterface,ElementsInterface> $parent
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $pId
 * @property-read ToOneRelationshipConfigBuilderInterface<ElementsInterface,ProcedureInterface> $procedure
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $category
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $title
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $icon
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $iconTitle
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $text
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $file
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $order
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $enabled
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $modifyDate
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $deleteDate
 * @property-read ToManyRelationshipConfigBuilderInterface<ElementsInterface,SingleDocumentInterface> $documents
 * @property-read ToManyRelationshipConfigBuilderInterface<ElementsInterface,ElementsInterface> $children
 * @property-read ToManyRelationshipConfigBuilderInterface<ElementsInterface,OrgaInterface> $organisations
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $designatedSwitchDate
 * @property-read AttributeConfigBuilderInterface<ElementsInterface> $permission
 */
class BaseElementsResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
