<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\InstitutionTagInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<InstitutionTagInterface>
 *
 * @property-read AttributeConfigBuilderInterface<InstitutionTagInterface> $label
 * @property-read ToManyRelationshipConfigBuilderInterface<InstitutionTagInterface,OrgaInterface> $taggedInstitutions
 * @property-read AttributeConfigBuilderInterface<InstitutionTagInterface> $creationDate
 * @property-read AttributeConfigBuilderInterface<InstitutionTagInterface> $modificationDate
 */
class BaseInstitutionTagResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
