<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureSubscriptionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ProcedureSubscriptionInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ProcedureSubscriptionInterface> $ident
 * @property-read ToOneRelationshipConfigBuilderInterface<ProcedureSubscriptionInterface,UserInterface> $user
 * @property-read AttributeConfigBuilderInterface<ProcedureSubscriptionInterface> $userEmail
 * @property-read AttributeConfigBuilderInterface<ProcedureSubscriptionInterface> $postcode
 * @property-read AttributeConfigBuilderInterface<ProcedureSubscriptionInterface> $city
 * @property-read AttributeConfigBuilderInterface<ProcedureSubscriptionInterface> $distance
 * @property-read AttributeConfigBuilderInterface<ProcedureSubscriptionInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ProcedureSubscriptionInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<ProcedureSubscriptionInterface> $modifiedDate
 * @property-read AttributeConfigBuilderInterface<ProcedureSubscriptionInterface> $deletedDate
 */
class BaseProcedureSubscriptionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
