<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ConsultationTokenInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\MailSendInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ConsultationTokenInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ConsultationTokenInterface> $note
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ConsultationTokenInterface,StatementInterface> $originalStatement
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ConsultationTokenInterface,MailSendInterface> $sentEmail
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ConsultationTokenInterface> $creationDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ConsultationTokenInterface> $modificationDate
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ConsultationTokenInterface,StatementInterface> $statement
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ConsultationTokenInterface> $token
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ConsultationTokenInterface> $manuallyCreated
 */
class BaseConsultationTokenResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
