<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\DepartmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\MasterToebInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<MasterToebInterface>
 *
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $ident
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $gatewayGroup
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $orgaName
 * @property-read ToOneRelationshipConfigBuilderInterface<MasterToebInterface,OrgaInterface> $orga
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $oId
 * @property-read ToOneRelationshipConfigBuilderInterface<MasterToebInterface,DepartmentInterface> $department
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $departmentName
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $sign
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $email
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $ccEmail
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $contactPerson
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $memo
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $comment
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $registered
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $districtHHMitte
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $districtEimsbuettel
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $districtAltona
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $districtHHNord
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $districtWandsbek
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $districtBergedorf
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $districtHarburg
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $districtBsu
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $documentRoughAgreement
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $documentAgreement
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $documentNotice
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $documentAssessment
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<MasterToebInterface> $modifiedDate
 */
class BaseMasterToebResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
