<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\AddressInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,AddressInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $code
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $street
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $street1
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $postalcode
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $city
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $region
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $state
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $postofficebox
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $phone
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $fax
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $email
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $url
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $modifiedDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressInterface> $houseNumber
 */
class BaseAddressResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
