<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\EntityContentChangeInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,EntityContentChangeInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChangeInterface> $created
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChangeInterface> $modified
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChangeInterface> $userId
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChangeInterface> $userName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChangeInterface> $entityType
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChangeInterface> $entityId
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChangeInterface> $entityField
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChangeInterface> $preUpdate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChangeInterface> $postUpdate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChangeInterface> $contentChange
 */
class BaseEntityContentChangeResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
