<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedurePhaseInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedurePhaseInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePhaseInterface> $key
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePhaseInterface> $step
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePhaseInterface> $startDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePhaseInterface> $endDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePhaseInterface> $creationDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePhaseInterface> $modificationDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePhaseInterface> $designatedPhase
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePhaseInterface> $designatedSwitchDate
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedurePhaseInterface,UserInterface> $designatedPhaseChangeUser
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePhaseInterface> $designatedEndDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePhaseInterface> $iteration
 */
class BaseProcedurePhaseResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
