<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ElementsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ParagraphInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ParagraphVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ParagraphVersionInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ParagraphVersionInterface,ParagraphInterface> $paragraph
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ParagraphVersionInterface,ProcedureInterface> $procedure
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ParagraphVersionInterface,ElementsInterface> $element
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersionInterface> $category
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersionInterface> $title
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersionInterface> $text
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersionInterface> $order
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersionInterface> $visible
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersionInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersionInterface> $versionDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersionInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersionInterface> $modifyDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersionInterface> $deleteDate
 */
class BaseParagraphVersionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
