<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\DepartmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DraftStatementInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DraftStatementVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ElementsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ParagraphVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SingleDocumentVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<DraftStatementVersionInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementVersionInterface,DraftStatementInterface> $draftStatement
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementVersionInterface,ProcedureInterface> $procedure
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $number
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $title
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $text
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementVersionInterface,ParagraphVersionInterface> $paragraph
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementVersionInterface,SingleDocumentVersionInterface> $document
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementVersionInterface,ElementsInterface> $element
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $polygon
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $file
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $mapFile
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementVersionInterface,OrgaInterface> $organisation
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $oName
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $dName
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementVersionInterface,DepartmentInterface> $department
 * @property-read ToOneRelationshipConfigBuilderInterface<DraftStatementVersionInterface,UserInterface> $user
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $uName
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $uStreet
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $uPostalCode
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $uCity
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $uEmail
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $feedback
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $externId
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $rejectedReason
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $negativ
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $submitted
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $released
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $showToAll
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $rejected
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $publicAllowed
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $publicUseName
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $publicDraftStatement
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $phase
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $versionDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $deletedDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $lastModifiedDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $submittedDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $releasedDate
 * @property-read AttributeConfigBuilderInterface<DraftStatementVersionInterface> $rejectedDate
 */
class BaseDraftStatementVersionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
