<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\StatementInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementVoteInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementVoteInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementVoteInterface,StatementInterface> $statement
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementVoteInterface,UserInterface> $user
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $firstName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $lastName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $active
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $modifiedDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $deletedDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $manual
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $createdByCitizen
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $organisationName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $departmentName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $userName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $userMail
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $userPostcode
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVoteInterface> $userCity
 */
class BaseStatementVoteResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
