<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SettingInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SettingInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SettingInterface> $ident
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SettingInterface,ProcedureInterface> $procedure
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SettingInterface,UserInterface> $user
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SettingInterface,OrgaInterface> $orga
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SettingInterface> $orgaId
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SettingInterface> $key
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SettingInterface> $content
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SettingInterface> $created
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SettingInterface> $modified
 */
class BaseSettingResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
