<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ElementsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SingleDocumentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SingleDocumentVersionInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SingleDocumentVersionInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SingleDocumentVersionInterface,SingleDocumentInterface> $singleDocument
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SingleDocumentVersionInterface,ProcedureInterface> $procedure
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SingleDocumentVersionInterface,ElementsInterface> $element
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $category
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $order
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $title
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $text
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $symbol
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $document
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $statementEnabled
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $visible
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $versionDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $modifyDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SingleDocumentVersionInterface> $deleteDate
 */
class BaseSingleDocumentVersionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
