<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\DevelopmentUserStoryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DevelopmentUserStoryVoteInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentUserStoryVoteInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryVoteInterface> $ident
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentUserStoryVoteInterface,OrgaInterface> $orga
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentUserStoryVoteInterface,UserInterface> $user
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentUserStoryVoteInterface,DevelopmentUserStoryInterface> $userStory
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryVoteInterface> $numberOfVotes
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryVoteInterface> $modifiedDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStoryVoteInterface> $createDate
 */
class BaseDevelopmentUserStoryVoteResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
