<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\StatementFieldDefinitionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementFormDefinitionInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFieldDefinitionInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinitionInterface> $creationDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinitionInterface> $modificationDate
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinitionInterface> $name
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFieldDefinitionInterface,StatementFormDefinitionInterface> $statementFormDefinition
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinitionInterface> $orderNumber
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinitionInterface> $enabled
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinitionInterface> $required
 */
class BaseStatementFieldDefinitionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
