<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\MailAttachmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\MailSendInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<MailSendInterface>
 *
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $idRef
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $template
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $to
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $from
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $cc
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $bcc
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $title
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $content
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $createdDate
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $sendDate
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $scope
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $status
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $context
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $context2
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $sendAttempt
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $lastStatusDate
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $errorCode
 * @property-read AttributeConfigBuilderInterface<MailSendInterface> $errorMessage
 * @property-read ToManyRelationshipConfigBuilderInterface<MailSendInterface,MailAttachmentInterface> $attachments
 */
class BaseMailSendResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
