<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\PlaceInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<PlaceInterface>
 *
 * @property-read AttributeConfigBuilderInterface<PlaceInterface> $description
 * @property-read AttributeConfigBuilderInterface<PlaceInterface> $solved
 * @property-read ToOneRelationshipConfigBuilderInterface<PlaceInterface,ProcedureInterface> $procedure
 * @property-read AttributeConfigBuilderInterface<PlaceInterface> $name
 * @property-read AttributeConfigBuilderInterface<PlaceInterface> $sortIndex
 */
class BasePlaceResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
