<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\HashedQueryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<HashedQueryInterface>
 *
 * @property-read AttributeConfigBuilderInterface<HashedQueryInterface> $hash
 * @property-read AttributeConfigBuilderInterface<HashedQueryInterface> $storedQuery
 * @property-read AttributeConfigBuilderInterface<HashedQueryInterface> $created
 * @property-read AttributeConfigBuilderInterface<HashedQueryInterface> $modified
 * @property-read ToOneRelationshipConfigBuilderInterface<HashedQueryInterface,ProcedureInterface> $procedure
 */
class BaseHashedQueryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
