<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\CustomerInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ReportEntryInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ReportEntryInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $category
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $group
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $level
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $userId
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $userName
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $sessionId
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $identifierType
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $identifier
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $mimeType
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $message
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $incoming
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntryInterface> $createDate
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ReportEntryInterface,CustomerInterface> $customer
 */
class BaseReportEntryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
