<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ManualListSortInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ManualListSortInterface>
 *
 * @property-read AttributeConfigBuilderInterface<ManualListSortInterface> $pId
 * @property-read AttributeConfigBuilderInterface<ManualListSortInterface> $context
 * @property-read AttributeConfigBuilderInterface<ManualListSortInterface> $namespace
 * @property-read AttributeConfigBuilderInterface<ManualListSortInterface> $idents
 */
class BaseManualListSortResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
