<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaStatusInCustomerInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\OrgaTypeInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<OrgaTypeInterface>
 *
 * @property-read AttributeConfigBuilderInterface<OrgaTypeInterface> $name
 * @property-read AttributeConfigBuilderInterface<OrgaTypeInterface> $label
 * @property-read ToManyRelationshipConfigBuilderInterface<OrgaTypeInterface,OrgaStatusInCustomerInterface> $orgaStatusInCustomers
 */
class BaseOrgaTypeResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
