<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\FaqCategoryInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\FaqInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\RoleInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<FaqInterface>
 *
 * @property-read AttributeConfigBuilderInterface<FaqInterface> $title
 * @property-read AttributeConfigBuilderInterface<FaqInterface> $text
 * @property-read AttributeConfigBuilderInterface<FaqInterface> $enabled
 * @property-read AttributeConfigBuilderInterface<FaqInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<FaqInterface> $modifyDate
 * @property-read ToManyRelationshipConfigBuilderInterface<FaqInterface,RoleInterface> $roles
 * @property-read ToOneRelationshipConfigBuilderInterface<FaqInterface,FaqCategoryInterface> $platformFaqCategory
 */
class BasePlatformFaqResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
