<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\ElementsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SingleDocumentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SingleDocumentVersionInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<SingleDocumentInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<SingleDocumentInterface,ProcedureInterface> $procedure
 * @property-read ToOneRelationshipConfigBuilderInterface<SingleDocumentInterface,ElementsInterface> $element
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $category
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $order
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $title
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $text
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $symbol
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $document
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $statementEnabled
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $visible
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $deleted
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $createDate
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $modifyDate
 * @property-read AttributeConfigBuilderInterface<SingleDocumentInterface> $deleteDate
 * @property-read ToManyRelationshipConfigBuilderInterface<SingleDocumentInterface,SingleDocumentVersionInterface> $versions
 */
class BaseSingleDocumentResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
