<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\CountyInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\DepartmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ElementsInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\MunicipalityInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ParagraphVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\PriorityAreaInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\SingleDocumentVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementFragmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementFragmentVersionInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\StatementInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\TagInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\UserInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<StatementFragmentInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,StatementInterface> $statement
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $displayId
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $text
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementFragmentInterface,TagInterface> $tags
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,ProcedureInterface> $procedure
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $voteAdvice
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $vote
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $created
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $modified
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $assignedToFbDate
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,DepartmentInterface> $department
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $considerationAdvice
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $consideration
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementFragmentInterface,CountyInterface> $counties
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementFragmentInterface,PriorityAreaInterface> $priorityAreas
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementFragmentInterface,MunicipalityInterface> $municipalities
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,DepartmentInterface> $archivedDepartment
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $archivedOrgaName
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $archivedDepartmentName
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $archivedVoteUserName
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,UserInterface> $assignee
 * @property-read ToManyRelationshipConfigBuilderInterface<StatementFragmentInterface,StatementFragmentVersionInterface> $versions
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $sortIndex
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,UserInterface> $modifiedByUser
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,DepartmentInterface> $modifiedByDepartment
 * @property-read AttributeConfigBuilderInterface<StatementFragmentInterface> $status
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,UserInterface> $lastClaimed
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,ElementsInterface> $element
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,ParagraphVersionInterface> $paragraph
 * @property-read ToOneRelationshipConfigBuilderInterface<StatementFragmentInterface,SingleDocumentVersionInterface> $document
 */
class BaseStatementFragmentResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
