<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\MailAttachmentInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\MailSendInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<MailAttachmentInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<MailAttachmentInterface,MailSendInterface> $mailSend
 * @property-read AttributeConfigBuilderInterface<MailAttachmentInterface> $filename
 * @property-read AttributeConfigBuilderInterface<MailAttachmentInterface> $deleteOnSent
 */
class BaseMailAttachmentResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
