<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\ResourceConfigBuilder;

use DemosEurope\DemosplanAddon\Contracts\Entities\CountyInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\CustomerCountyInterface;
use DemosEurope\DemosplanAddon\Contracts\Entities\CustomerInterface;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<CustomerCountyInterface>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<CustomerCountyInterface,CustomerInterface> $customer
 * @property-read ToOneRelationshipConfigBuilderInterface<CustomerCountyInterface,CountyInterface> $county
 * @property-read AttributeConfigBuilderInterface<CustomerCountyInterface> $eMailAddress
 */
class BaseCustomerCountyResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
