services:
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  DemosEurope\DemosplanAddon\:
    resource: '../src/*'

  DemosEurope\DemosplanAddon\Controller\APIController:
    arguments:
      $resourceTypeProvider: '@demosplan\DemosPlanCoreBundle\Logic\ApiRequest\PrefilledResourceTypeProvider'

  DemosEurope\DemosplanAddon\Contracts\Config\GlobalConfigInterface:
    class: 'demosplan\DemosPlanCoreBundle\Resources\config\GlobalConfig'
    public: true

  DemosEurope\DemosplanAddon\Permission\PermissionEvaluatorInterface: '@demosplan\DemosPlanCoreBundle\Permissions\Permissions'

  DemosEurope\DemosplanAddon\Contracts\ResourceType\:
    resource: '../src/Contracts/ResourceType'
    public: true
