<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read ProcedurePath $procedure
 * @property-read BoilerplatePath $boilerplates
 * @property-read End $title
 * @property-read End $description
 * @property-read End $createDate
 * @property-read End $modifyDate
 */
class BoilerplateCategoryPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
