<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident
 * @property-read OrgaPath $orga
 * @property-read UserPath $user
 * @property-read DevelopmentUserStoryPath $userStory
 * @property-read End $numberOfVotes
 * @property-read End $modifiedDate
 * @property-read End $createDate
 */
class DevelopmentUserStoryVotePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
