<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read ProcedurePath $procedure
 * @property-read End $number
 * @property-read End $title
 * @property-read End $text
 * @property-read ParagraphVersionPath $paragraph
 * @property-read SingleDocumentVersionPath $document
 * @property-read ElementsPath $element
 * @property-read End $polygon
 * @property-read End $file
 * @property-read DraftStatementFilePath $files
 * @property-read End $mapFile
 * @property-read OrgaPath $organisation
 * @property-read End $oName
 * @property-read End $dName
 * @property-read DepartmentPath $department
 * @property-read UserPath $user
 * @property-read End $uName
 * @property-read End $uStreet
 * @property-read End $houseNumber
 * @property-read End $uPostalCode
 * @property-read End $uCity
 * @property-read End $uEmail
 * @property-read End $uFeedback
 * @property-read End $feedback
 * @property-read End $externId
 * @property-read End $rejectedReason
 * @property-read End $negativ
 * @property-read End $submitted
 * @property-read End $released
 * @property-read End $showToAll
 * @property-read End $deleted
 * @property-read End $rejected
 * @property-read End $publicAllowed
 * @property-read End $publicUseName
 * @property-read End $publicDraftStatement
 * @property-read End $represents
 * @property-read End $phase
 * @property-read End $createdDate
 * @property-read End $deletedDate
 * @property-read End $lastModifiedDate
 * @property-read End $submittedDate
 * @property-read End $releasedDate
 * @property-read End $rejectedDate
 * @property-read DraftStatementVersionPath $versions
 * @property-read StatementAttributePath $statementAttributes
 * @property-read End $miscData
 * @property-read End $anonymous
 */
class DraftStatementPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
