<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read End $created
 * @property-read End $modified
 * @property-read End $userId
 * @property-read End $userName
 * @property-read End $entityType
 * @property-read End $entityId
 * @property-read End $entityField
 * @property-read End $preUpdate
 * @property-read End $postUpdate
 * @property-read End $contentChange
 */
class EntityContentChangePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
