<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read ProcedurePath $procedure
 * @property-read End $creationDate
 * @property-read End $modificationDate
 * @property-read End $idExportable
 * @property-read End $statementNameExportable
 * @property-read End $creationDateExportable
 * @property-read End $procedureNameExportable
 * @property-read End $procedurePhaseExportable
 * @property-read End $votesNumExportable
 * @property-read End $userStateExportable
 * @property-read End $userGroupExportable
 * @property-read End $userOrganisationExportable
 * @property-read End $userPositionExportable
 * @property-read End $institutionExportable
 * @property-read End $publicParticipationExportable
 * @property-read End $orgaNameExportable
 * @property-read End $departmentNameExportable
 * @property-read End $submitterNameExportable
 * @property-read End $showInPublicAreaExportable
 * @property-read End $documentExportable
 * @property-read End $paragraphExportable
 * @property-read End $filesExportable
 * @property-read End $attachmentsExportable
 * @property-read End $priorityExportable
 * @property-read End $emailExportable
 * @property-read End $phoneNumberExportable
 * @property-read End $streetExportable
 * @property-read End $streetNumberExportable
 * @property-read End $postalCodeExportable
 * @property-read End $cityExportable
 * @property-read End $institutionOrCitizenExportable
 */
class ExportFieldsConfigurationPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
