<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read End $entityId
 * @property-read End $entityClass
 * @property-read End $entityField
 * @property-read End $createDate
 * @property-read End $modifyDate
 * @property-read End $order
 * @property-read End $fileString
 * @property-read FilePath $file
 * @property-read End $publicAllowed
 */
class FileContainerPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
