<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read End $ident
 * @property-read End $hash
 * @property-read End $name
 * @property-read End $description
 * @property-read End $path
 * @property-read End $filename
 * @property-read End $tags
 * @property-read End $author
 * @property-read End $application
 * @property-read End $mimetype
 * @property-read End $created
 * @property-read End $modified
 * @property-read End $validUntil
 * @property-read End $deleted
 * @property-read End $statDown
 * @property-read End $infected
 * @property-read End $lastVScan
 * @property-read End $blocked
 * @property-read End $size
 * @property-read ProcedurePath $procedure
 */
class FilePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
