<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident
 * @property-read End $url
 * @property-read End $closed
 * @property-read End $closingReason
 * @property-read End $progression
 * @property-read End $createDate
 * @property-read End $modifyDate
 */
class ForumThreadPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
