<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident
 * @property-read End $bplan
 * @property-read End $defaultVisibility
 * @property-read End $deleted
 * @property-read End $legend
 * @property-read End $layers
 * @property-read End $name
 * @property-read End $opacity
 * @property-read End $order
 * @property-read End $projectionLabel
 * @property-read End $projectionValue
 * @property-read End $procedureId
 * @property-read End $print
 * @property-read End $scope
 * @property-read End $scope1
 * @property-read End $type
 * @property-read End $serviceType
 * @property-read End $capabilities
 * @property-read End $tileMatrixSet
 * @property-read End $url
 * @property-read End $enabled
 * @property-read End $gId
 * @property-read End $layerVersion
 * @property-read End $xplan
 * @property-read End $createDate
 * @property-read End $modifyDate
 * @property-read End $deleteDate
 * @property-read ContextualHelpPath $contextualHelp
 * @property-read GisLayerCategoryPath $category
 * @property-read End $treeOrder
 * @property-read End $userToggleVisibility
 * @property-read End $visibilityGroupId
 * @property-read End $isMiniMap
 */
class GisLayerPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
