<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident
 * @property-read MasterToebPath $masterToeb
 * @property-read End $gatewayGroup
 * @property-read End $orgaName
 * @property-read OrgaPath $orga
 * @property-read DepartmentPath $department
 * @property-read End $departmentName
 * @property-read End $sign
 * @property-read End $email
 * @property-read End $ccEmail
 * @property-read End $contactPerson
 * @property-read End $memo
 * @property-read End $comment
 * @property-read End $registered
 * @property-read End $districtHHMitte
 * @property-read End $districtEimsbuettel
 * @property-read End $districtAltona
 * @property-read End $districtHHNord
 * @property-read End $districtWandsbek
 * @property-read End $districtBergedorf
 * @property-read End $districtHarburg
 * @property-read End $districtBsu
 * @property-read End $documentRoughAgreement
 * @property-read End $documentAgreement
 * @property-read End $documentNotice
 * @property-read End $documentAssessment
 * @property-read End $createdDate
 * @property-read End $modifiedDate
 * @property-read End $versionDate
 */
class MasterToebVersionPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
