<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $uniqueId
 * @property-read End $id
 * @property-read End $postcode
 * @property-read End $city
 * @property-read End $municipalCode
 * @property-read End $state
 * @property-read End $lat
 * @property-read End $lon
 */
class OpenGeoDbShortTablePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
