<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read End $name
 * @property-read End $shortUrl
 * @property-read End $orgaName
 * @property-read OrgaPath $orga
 * @property-read End $desc
 * @property-read ProcedurePhasePath $phase
 * @property-read End $logo
 * @property-read End $externId
 * @property-read End $plisId
 * @property-read End $closed
 * @property-read End $deleted
 * @property-read End $master
 * @property-read End $masterTemplate
 * @property-read End $externalName
 * @property-read End $externalDesc
 * @property-read End $publicParticipation
 * @property-read ProcedurePhasePath $publicParticipationPhase
 * @property-read End $publicParticipationContact
 * @property-read End $publicParticipationPublicationEnabled
 * @property-read End $locationName
 * @property-read End $locationPostCode
 * @property-read End $municipalCode
 * @property-read End $ars
 * @property-read End $createdDate
 * @property-read End $closedDate
 * @property-read End $deletedDate
 * @property-read OrgaPath $organisation
 * @property-read OrgaPath $planningOffices
 * @property-read OrgaPath $dataInputOrganisations
 * @property-read ProcedureSettingsPath $settings
 * @property-read TagTopicPath $topics
 * @property-read NotificationReceiverPath $notificationReceivers
 * @property-read ElementsPath $elements
 * @property-read UserPath $authorizedUsers
 * @property-read End $agencyMainEmailAddress
 * @property-read EmailAddressPath $agencyExtraEmailAddresses
 * @property-read CustomerPath $customer
 * @property-read ProcedureCategoryPath $procedureCategories
 * @property-read StatementPath $statements
 * @property-read SurveyPath $surveys
 * @property-read ProcedureTypePath $procedureType
 * @property-read StatementFormDefinitionPath $statementFormDefinition
 * @property-read ProcedureBehaviorDefinitionPath $procedureBehaviorDefinition
 * @property-read ProcedureUiDefinitionPath $procedureUiDefinition
 * @property-read ExportFieldsConfigurationPath $exportFieldsConfigurations
 * @property-read FilePath $files
 * @property-read End $xtaPlanId
 * @property-read PlacePath $segmentPlaces
 * @property-read SlugPath $currentSlug
 * @property-read SlugPath $slugs
 */
class ProcedurePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
