<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read End $creationDate
 * @property-read End $modificationDate
 * @property-read ProcedurePath $procedure
 * @property-read ProcedureTypePath $procedureType
 * @property-read End $mapHintDefault
 * @property-read End $statementFormHintStatement
 * @property-read End $statementFormHintPersonalData
 * @property-read End $statementFormHintRecheck
 * @property-read End $statementPublicSubmitConfirmationText
 */
class ProcedureUiDefinitionPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
