<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read End $streetName
 * @property-read End $streetNumber
 * @property-read End $city
 * @property-read End $postalCode
 * @property-read End $emailAddress
 * @property-read StatementPath $similarForeignStatements
 * @property-read End $fullName
 * @property-read ProcedurePath $procedure
 */
class ProcedurePersonPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
