<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident
 * @property-read UserPath $user
 * @property-read End $userEmail
 * @property-read End $postcode
 * @property-read End $city
 * @property-read End $distance
 * @property-read End $deleted
 * @property-read End $createdDate
 * @property-read End $modifiedDate
 * @property-read End $deletedDate
 */
class ProcedureSubscriptionPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
