<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read End $mapExtent
 * @property-read End $startScale
 * @property-read End $availableScale
 * @property-read End $boundingBox
 * @property-read End $informationUrl
 * @property-read End $defaultLayer
 * @property-read End $territory
 * @property-read End $coordinate
 * @property-read End $planEnable
 * @property-read End $planText
 * @property-read End $planPDF
 * @property-read End $planPara1PDF
 * @property-read End $planPara2PDF
 * @property-read End $planDrawText
 * @property-read End $planDrawPDF
 * @property-read End $emailTitle
 * @property-read End $emailText
 * @property-read End $emailCc
 * @property-read End $links
 * @property-read ProcedurePath $procedure
 * @property-read End $pictogram
 * @property-read End $designatedPhase
 * @property-read End $designatedPublicPhase
 * @property-read End $designatedSwitchDate
 * @property-read End $designatedPublicSwitchDate
 * @property-read UserPath $designatedPhaseChangeUser
 * @property-read UserPath $designatedPublicPhaseChangeUser
 * @property-read End $designatedEndDate
 * @property-read End $designatedPublicEndDate
 * @property-read End $sendMailsToCounties
 * @property-read End $planningArea
 * @property-read End $scales
 * @property-read End $legalNotice
 * @property-read End $copyright
 * @property-read End $mapHint
 * @property-read ProcedurePath $allowedSegmentAccessProcedures
 */
class ProcedureSettingsPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
