<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read End $category
 * @property-read End $group
 * @property-read End $level
 * @property-read End $userId
 * @property-read End $userName
 * @property-read End $sessionId
 * @property-read End $identifierType
 * @property-read End $identifier
 * @property-read End $mimeType
 * @property-read End $message
 * @property-read End $incoming
 * @property-read End $createDate
 * @property-read CustomerPath $customer
 */
class ReportEntryPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
