<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $sess_id
 * @property-read End $sess_data
 * @property-read End $sess_lifetime
 * @property-read End $sess_time
 */
class SessionsPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
