<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read StatementPath $statement
 * @property-read UserPath $user
 * @property-read End $firstName
 * @property-read End $lastName
 * @property-read End $active
 * @property-read End $deleted
 * @property-read End $createdDate
 * @property-read End $modifiedDate
 * @property-read End $deletedDate
 * @property-read End $manual
 * @property-read End $createdByCitizen
 * @property-read End $organisationName
 * @property-read End $departmentName
 * @property-read End $userName
 * @property-read End $userMail
 * @property-read End $userPostcode
 * @property-read End $userCity
 */
class StatementVotePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
