<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read StatementPath $statement
 * @property-read End $authorName
 * @property-read End $authorFeedback
 * @property-read End $submitUId
 * @property-read End $submitName
 * @property-read End $orgaName
 * @property-read End $orgaDepartmentName
 * @property-read End $caseWorkerName
 * @property-read End $orgaStreet
 * @property-read End $houseNumber
 * @property-read End $orgaPostalCode
 * @property-read End $orgaCity
 * @property-read End $orgaEmail
 * @property-read End $authoredDate
 * @property-read End $submitOrgaId
 * @property-read End $miscData
 */
class StatementMetaPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
