<?php

declare(strict_types=1);

namespace DemosEurope\DemosplanAddon\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id
 * @property-read End $isAgreed
 * @property-read End $text
 * @property-read End $textReview
 * @property-read End $createdDate
 * @property-read SurveyPath $survey
 * @property-read UserPath $user
 */
class SurveyVotePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
